# Form implementation generated from reading ui file 'D:\TDT!!!\E68\ui\order_detail.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OrderDetailDialog(object):
    def setupUi(self, OrderDetailDialog):
        OrderDetailDialog.setObjectName("OrderDetailDialog")
        OrderDetailDialog.resize(400, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(OrderDetailDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelCategory = QtWidgets.QLabel(parent=OrderDetailDialog)
        self.labelCategory.setObjectName("labelCategory")
        self.verticalLayout.addWidget(self.labelCategory)
        self.comboBoxCategories = QtWidgets.QComboBox(parent=OrderDetailDialog)
        self.comboBoxCategories.setObjectName("comboBoxCategories")
        self.verticalLayout.addWidget(self.comboBoxCategories)
        self.labelProduct = QtWidgets.QLabel(parent=OrderDetailDialog)
        self.labelProduct.setObjectName("labelProduct")
        self.verticalLayout.addWidget(self.labelProduct)
        self.comboBoxProducts = QtWidgets.QComboBox(parent=OrderDetailDialog)
        self.comboBoxProducts.setObjectName("comboBoxProducts")
        self.verticalLayout.addWidget(self.comboBoxProducts)
        self.labelQuantity = QtWidgets.QLabel(parent=OrderDetailDialog)
        self.labelQuantity.setObjectName("labelQuantity")
        self.verticalLayout.addWidget(self.labelQuantity)
        self.spinBoxQuantity = QtWidgets.QSpinBox(parent=OrderDetailDialog)
        self.spinBoxQuantity.setMinimum(1)
        self.spinBoxQuantity.setMaximum(100)
        self.spinBoxQuantity.setObjectName("spinBoxQuantity")
        self.verticalLayout.addWidget(self.spinBoxQuantity)
        self.btnAdd = QtWidgets.QPushButton(parent=OrderDetailDialog)
        self.btnAdd.setObjectName("btnAdd")
        self.verticalLayout.addWidget(self.btnAdd)
        self.tableOrderDetails = QtWidgets.QTableWidget(parent=OrderDetailDialog)
        self.tableOrderDetails.setObjectName("tableOrderDetails")
        self.tableOrderDetails.setColumnCount(0)
        self.tableOrderDetails.setRowCount(0)
        self.verticalLayout.addWidget(self.tableOrderDetails)
        self.btnSave = QtWidgets.QPushButton(parent=OrderDetailDialog)
        self.btnSave.setObjectName("btnSave")
        self.verticalLayout.addWidget(self.btnSave)

        self.retranslateUi(OrderDetailDialog)
        QtCore.QMetaObject.connectSlotsByName(OrderDetailDialog)

    def retranslateUi(self, OrderDetailDialog):
        _translate = QtCore.QCoreApplication.translate
        OrderDetailDialog.setWindowTitle(_translate("OrderDetailDialog", "Thêm vật phẩm vào hóa đơn"))
        self.labelCategory.setText(_translate("OrderDetailDialog", "Category"))
        self.labelProduct.setText(_translate("OrderDetailDialog", "Product"))
        self.labelQuantity.setText(_translate("OrderDetailDialog", "Quantity"))
        self.btnAdd.setText(_translate("OrderDetailDialog", "ADD"))
        self.btnSave.setText(_translate("OrderDetailDialog", "Save Order"))
