# Form implementation generated from reading ui file 'D:\TDT!!!\E87\ui\DetailInfo.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(444, 303)
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 421, 241))
        self.groupBox.setObjectName("groupBox")
        self.labelID = QtWidgets.QLabel(parent=self.groupBox)
        self.labelID.setGeometry(QtCore.QRect(40, 30, 60, 30))
        self.labelID.setObjectName("labelID")
        self.lineEditName = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditName.setGeometry(QtCore.QRect(90, 30, 300, 21))
        self.lineEditName.setObjectName("lineEditName")
        self.labelName = QtWidgets.QLabel(parent=self.groupBox)
        self.labelName.setGeometry(QtCore.QRect(30, 70, 60, 30))
        self.labelName.setObjectName("labelName")
        self.lineEditID = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditID.setGeometry(QtCore.QRect(90, 70, 300, 21))
        self.lineEditID.setObjectName("lineEditID")
        self.lineEditPhone = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditPhone.setGeometry(QtCore.QRect(90, 110, 300, 21))
        self.lineEditPhone.setObjectName("lineEditPhone")
        self.labelPhone = QtWidgets.QLabel(parent=self.groupBox)
        self.labelPhone.setGeometry(QtCore.QRect(30, 110, 60, 30))
        self.labelPhone.setObjectName("labelPhone")
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditEmail.setGeometry(QtCore.QRect(90, 150, 300, 21))
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.labelEmail = QtWidgets.QLabel(parent=self.groupBox)
        self.labelEmail.setGeometry(QtCore.QRect(30, 150, 60, 30))
        self.labelEmail.setObjectName("labelEmail")
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(100, 190, 75, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 190, 75, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.labelTitle = QtWidgets.QLabel(parent=Dialog)
        self.labelTitle.setGeometry(QtCore.QRect(180, 10, 120, 30))
        self.labelTitle.setObjectName("labelTitle")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Customer Details:"))
        self.labelID.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Id:</span></p></body></html>"))
        self.labelName.setText(_translate("Dialog", "Name:"))
        self.labelPhone.setText(_translate("Dialog", "Phone:"))
        self.labelEmail.setText(_translate("Dialog", "Email:"))
        self.pushButton.setText(_translate("Dialog", "Save"))
        self.pushButton_2.setText(_translate("Dialog", "Remove"))
        self.labelTitle.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:700; color:#aa55ff;\">Detail Infor</span></p></body></html>"))
